Layout/LineLength:
  Max: 200
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
