# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 454976c62404156a63678560f182cf7a6fc8cdf2b44c4a8e803883a474b31d5a621864b9c0b5486cae3085f1443db035d9611e9209acb2847997a18704413dcc

test:
  secret_key_base: 85d7ac651c6efb7396763ce8ab897effbe21931230dbf266edbb30effd850b47e707a0bb046fed172b295ad27e4f1c777e8613a7730d2745f694ce0b00cdd116

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
