streak:
  api_cipher_random_key: <%= ENV.fetch("STREAK_API_CIPHER_RANDOM_KEY", Rails.application.credentials[:streak][:api_cipher_random_key]) %>,
  api_cipher_random_iv: <%= ENV.fetch("STREAK_API_CIPHER_RANDOM_IV", Rails.application.credentials[:streak][:api_cipher_random_iv])  %>,
  api_key: <%= ENV.fetch("STREAK_API_KEY", Rails.application.credentials[:streak][:api_key]) %>
  create_boxes: <%= ENV.fetch("CREATE_STREAK_BOXES", "false") %>
emails:
  auto_quoting_enabled: <%= ENV.fetch("AUTO_QUOTING_ENABLED", "false") %>
  auto_quoting_delay: 10