streak:
  create_boxes: <%= ENV.fetch("CREATE_STREAK_BOXES", "false") %>
emails:
  auto_quote_delay: <%= ENV.fetch("AUTO_QUOTE_DELAY", 0) %>
  disable_campaign_monitor: <%= ENV.fetch("DISABLE_CAMPAIGN_MONITOR", "false") %>
  use_cm_for_auto_quote_emails: <%= ENV.fetch("USE_CM_FOR_AUTO_QUOTE_EMAILS", "true") %>
  use_cm_for_confirmation_emails: <%= ENV.fetch("USE_CM_FOR_CONFIRMATION_EMAILS", "true") %>
