config:
  auto_quote_delay: <%= ENV.fetch 'CONFIG_AUTO_QUOTE_DELAY', 0 %>
  create_streak_boxes: <%= ENV.fetch 'CONFIG_CREATE_STREAK_BOXES', 'false' %>
  auto_quote_emails: <%= ENV.fetch 'CONFIG_AUTO_QUOTE_EMAILS', 'disabled' %>
  confirmation_emails: <%= ENV.fetch 'CONFIG_CONFIRMATION_EMAILS', 'disabled' %>
  campaign_monitor: <%= ENV.fetch 'CONFIG_CAMPAIGN_MONITOR', 'enabled' %>
  transactional_emails: <%= ENV.fetch 'CONFIG_TRANSACTIONAL_EMAILS', 'disabled' %>
