gmail:
  subject_append: <%= Rails.application.credentials[:gmail][:development][:subject_append] %>
  labels:
    new_design_requests: Label_5143087514283227928
    design_requests: Label_2918953571817969548
    appointment_requests: Label_7177529587396720741
streak:
  api_key: <%= Rails.application.credentials[:streak][:development][:api_key] %>
  pipeline_key: <%= Rails.application.credentials[:streak][:development][:pipeline_key] %>
emails:
  deliver_start_design: true
  deliver_opt_in: true
  notification_recipients:
    - stephen@customtattoodesign.ca
  autoquote_bcc_recipients:
    - stephen@customtattoodesign.ca
  lee: leeroller@customtattoodesign.ca
  system: sales@customtattoodesign.ca
  mailer: mailer@customtattoodesign.ca
  csr: mailer@customtattoodesign.ca
  sales_manager: gdietrich@customtattoodesign.ca 