gmail:
  subject_append: <%= Rails.application.credentials[:gmail][:production][:subject_append] %>
  labels:
    new_design_requests: Label_6157564878440197778
    design_requests: Label_2606897481654667624
    appointment_requests: Label_7177529587396720741
streak:
  api_key: <%= Rails.application.credentials[:streak][:production][:api_key] %>
  pipeline_key: <%= Rails.application.credentials[:streak][:production][:pipeline_key] %>
emails:
  deliver_start_design: true
  deliver_opt_in: true
  notification_recipients:
    - leeroller@customtattoodesign.ca
    - carmelle@customtattoodesign.ca
    - johnd@customtattoodesign.ca
  autoquote_bcc_recipients:
    - leeroller@customtattoodesign.ca
  lee: leeroller@customtattoodesign.ca
  system: sales@customtattoodesign.ca
  mailer: mailer@customtattoodesign.ca
  csr: mailer@customtattoodesign.ca
  sales_manager: gdietrich@customtattoodesign.ca 
