gmail:
  subject_append: <%= Rails.application.credentials[:gmail][:staging][:subject_append] %>
  labels:
    new_design_requests: Label_511143588161420553
    design_requests: Label_3869020623180863137
    appointment_requests: Label_7177529587396720741
streak:
  api_key: <%= Rails.application.credentials[:streak][:staging][:api_key] %>
  pipeline_key: <%= Rails.application.credentials[:streak][:staging][:pipeline_key] %>
emails:
  deliver_start_design: true
  deliver_opt_in: true
  notification_recipients:
    - leeroller@customtattoodesign.ca
    - carmelle@customtattoodesign.ca
    - johnd@customtattoodesign.ca
  lee: leeroller@customtattoodesign.ca
  system: sales@customtattoodesign.ca
  mailer: mailer@customtattoodesign.ca
  csr: mailer@customtattoodesign.ca
  sales_manager: gdietrich@customtattoodesign.ca 
