gmail:
  labels:
    design_requests: "Label_3869020623180863137"
    appointment_requests: "Label_7177529587396720741"
  smtp_settings:
    address: <%= ENV["SMTP_ADDRESS"] %>
    port: <%= ENV["SMTP_PORT"] %>
    domain: customtattoodesign.ca
    user_name: <%= ENV["SMTP_USER_NAME"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
    authentication: login
    enable_starttls_auto: true
streak:
  pipeline_key: "agxzfm1haWxmb29nYWVyPAsSDE9yZ2FuaXphdGlvbiIVY3VzdG9tdGF0dG9vZGVzaWduLmNhDAsSCFdvcmtmbG93GICA0t2vy-cLDA"