gmail:
  labels:
    new_design_requests: Label_5143087514283227928
    design_requests: Label_2918953571817969548
    appointment_requests: Label_7177529587396720741
streak:
  api_key: <%= Rails.application.credentials[:streak][:test][:api_key] %>
  pipeline_key: <%= Rails.application.credentials[:streak][:test][:pipeline_key] %>
emails:
  deliver_start_design: true
  deliver_opt_in: true
  notification_recipients:
    - mailer@ctd-sales.dev
  auto_quoting_delay: 0
  lee: leeroller@ctd-sales.dev
  system: sales@ctd-sales.dev
  mailer: mailer@ctd-sales.dev
  csr: carmelle@ctd-sales.dev
  sales_manager: geoff@ctd-sales.dev
